### ISSUE TITLE
对无效字符的命名规范疑问

### ISSUE THREAD

**Issue by Endermanpoi** [vcb-s/VCB-S_Collation#1]
提出这个疑问是看到命名实例中看到有出现`/ ?`，win文件路径不允许使用`\ / : * ? "< > |`这些通配符之类特殊符号，这算是规范的一个BUG吧。看手头下载的FSN-HF是直接去掉了`/`，不知有没有对于这个特殊字符处理规范（难道说直接怼？）。

**Comment by icefiresS** [comment]
出现非法字符时, 目前暂行的命名原则是: 
1. 若删去字符不会引起混淆, 则不保留;
2. 若删去字符会引起混淆 (如点兔一期与二期命名是通过问号的数量来区分的), 则
    - 在Unicode中寻找外观相似的半角字符替代;
    - 如果不存在, 则使用全角字符替代.

例如, 现行规范中对于正斜线和冒号有如下推荐替代 (非强制):
```
*需要在名称里使用正斜线的请使用：⁄  注意这个符号一般情况下需要左右各配一个空格 

*需要在名称里使用冒号的请使用：꞉
```
`꞉` 出自 [Unicode Latin Extended D](https://en.wikipedia.org/wiki/Latin_Extended-D), 编码是U+A789;
`⁄ ` 出自[General Punctuation](https://en.wikipedia.org/wiki/General_Punctuation), 编码是U+2044.

**Comment by wfwf1997** [comment]
`dev` 分支内有稍修改，欢迎讨论。
